### ISSUE TITLE
textAlign not workiing on iOS

### ISSUE THREAD

**Issue by skptl** [wix/react-native-autogrow-textinput#14]
For some reasons, placeholder text doesn't seem to obey `textAlign: 'center'` style prop. The actual text is center, its just the placeholder.
Thanks.

**Comment by artald** [comment]
@skptl tried it just now in the example project and it worked as expected.
Which RN version are you using? Which version of the package?

**Comment by skptl** [comment]
@artald Thanks for the quick response!
I am sorry but I tried cleaning node_modules as it was working in the example and it is all good. I did tried it before I opened up the issue, it was weird on my part. Anyways thanks for checking in, I appreciate that.
