### ISSUE TITLE
Placeholder's default text color

### ISSUE THREAD

**Issue by LAITONEN** [wix/react-native-autogrow-textinput#17]
Hello!
Have noticed that the default text color for the component's placeholder's text is black, while in the TextInput component, that is a basis of this component, the default color is '#C7C7CD'. Same with your example. On the gif, the color is '#C7C7CD', in the code it is black.

This is a minor issue, but still solving it could save up some time for the newcomers. So that they do not need to google "how to set text color of the placeholder" and "what is the default color of the placeholder".

Just add this property (placeholderTextColor='#C7C7CD') to your example code.

Good luck! Thanks for the great component!

P.S. Also, I have noticed, that the placeholder's text does not stay in the vertical center of the component on-screen. But this might be something personal, have not digged into.

**Comment by artald** [comment]
thanks @LAITONEN 

this is probably something that has change at some point in react-native, I don't know which version exactly, but when using the latest (currently 44.2) it's indeed black. When the video was recorded it worked properly without specifying the `placeholderTextColor`. The demo project now uses this prop.
