### ISSUE TITLE
FYI: All multiline textinputs are autogrowing by default on iOS

### ISSUE THREAD

**Issue by shergin** [wix/react-native-autogrow-textinput#19]
LMK if you have questions.

I will also work on same functionality on Android, if you have ideas how it should be implemented, please share them with me.

**Comment by artald** [comment]
@shergin that's great news! thanks for the update!
This means that I can just remove the manual height handling for iOS...

A couple of questions:

1. In what version of RN did this feature become available?
2. Can it be controlled via some prop? (turn it off/on for example)

**Comment by artald** [comment]
Just published version `4.0.0` which uses the default RN implementation for auto expanding, Hopefully at some point this will be supported on Android as well so it can be simplified and all other hacks can be removed.
