### ISSUE TITLE
Doesn't work with setNativeProps

### ISSUE THREAD

**Issue by JonathanWi** [wix/react-native-autogrow-textinput#2]
Hey!

Cool component but it appears that I can't access setNativeProps since I can't pass down a ref to the TextInput. Passing it as a props might be a viable solution, but you need to expose the ref on the TextInput inside :)

Cheers

**Comment by artald** [comment]
Thanks for the suggestion @JonathanWi.

The latest version (0.0.6) now supports setNativeProps. You can just call it on your own ref and it will be passed to the inner one. Here's an example:

```jsx
componentDidMount() {
  this._textInput.setNativeProps({text: 'my text'});
}

render() {
  return (
    <View style={styles.container}>
      <AutoGrowingTextInput style={styles.textInput}
                            placeholder={'Your Message'}
                            ref={(r) => { this._textInput = r; }} 
      />
    </View>
  );
}
```
