### ISSUE TITLE
Not content auto scroll-down when typing

### ISSUE THREAD

**Issue by janaka120** [wix/react-native-autogrow-textinput#24]
When I'm typing multiple line sentence on **autogrow-textinput**. it always shows only first three lines only.
I have to manually scroll down to the bottom. To see what I am typing. 

`<AutoGrowingTextInput
      ref={(r) => { this._textInput = r; }}
      value={this.props.text}
      onChange={(event) => this.onChangeText(event.nativeEvent.text)}
      style={styles.editor}
      placeholder={"Type here"}
      placeholderTextColor="#a5b3b6"
      minHeight={30}
      maxHeight={60}
/>`

react-native-autogrow-textinput: 4.1.0
react-native: 0.38
os: android 7.0
device: sumsung A5

**Comment by zeusi83** [comment]
I'm afraid it's a TextInput limit.

**Comment by janaka120** [comment]
I think that part was working in TextInput.

**Comment by zeusi83** [comment]
It does not work for me...

**Comment by janaka120** [comment]
sorry about that. I am using RN-0.38

**Comment by artald** [comment]
@janaka120 you're using the `maxHeight` prop which sets a limit for the growing. You can either increase it or remove it completely.

**Comment by zeusi83** [comment]
I think that is not a solution. It should be possibile to limit the height of the component, and still see text you are typing.

**Comment by artald** [comment]
Actually, the solution of letting the input grow indefinitely is a common solution and depending on your use-case, this is probably the best solution UX-wise.

Regarding the scrolling, as far as I know this is an issue with RN and not related to this package which only utilizes the available callbacks from RN `TextInput`. That said, I recently added a custom native solution that will auto scroll to the text input caret in case it is covered by the keyboard (useful if you have a form-like kind of screen that has an auto-growing field). Not sure if this will help your case but you can try it by linking the `AutoGrowTextInput` ios project (only available on iOS at the moment).

**Comment by zeusi83** [comment]
I agree this is a RN issue. I was not criticizing this package.
