### ISSUE TITLE
Doesn't expose TextFields clear or isFocused methods

### ISSUE THREAD

**Issue by ckuijjer** [wix/react-native-autogrow-textinput#8]
Hi! Nice package!

I noticed it doesn't expose the internal TextFields clear or isFocused methods. I've created a small pull request that implements these

**Comment by artald** [comment]
thanks @ckuijjer!
I merged your PR. It's now published and available in version `2.1.1`

**Comment by ckuijjer** [comment]
awesome! thanks!
